name : My second work-flow

on: push


jobs : 
     second_job :
         runs-on : ubuntu-latest
         steps :
          - name: Checkout
            uses: actions/checkout@v4

          
         
          - name : list the files
            run  : |
                echo "my Second Git Hub Actions"
                ls -l
               

          - name : Install cowsay
            run: sudo apt-get install cowsay -y     
          - name : Generate ASCII Artwork
            run:   cowsay -f dragon "Run for cover ,I am a Dragon ...RAWR" >>dragon.txt   

          

            #- name : read the files
            #run: cat README.md


